### ISSUE TITLE
Hack 3.002 released, fixes bad rendering on Windows

### ISSUE THREAD

**Issue by glebd** [vikky49/patchedFonts-Ligatures#1]
Excellent work! Unfortunately, you based ligaturized Hack on v3.001 which had a rendering bug on Windows. They have now released a fixed version, and it would be great if you updated your Hack version based on that. Thanks!

**Comment by vikky49** [comment]
Done ..Re patched it and uploaded it

**Comment by glebd** [comment]
Fantastic, much appreciated!
